version: '3.9'

services:
  db-postgresql:
    image: postgres:15.2-alpine3.17
    container_name: db_postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

# docker compose up -d